### ISSUE TITLE
Support also Windows (without MPI)

### ISSUE THREAD

**Issue by paugier** [conda-forge/fluidfft-feedstock#2] opened 2019-04-16 16:15 UTC
It should not be difficult to build also for Windows without MPI support.

**Comment by paugier** [comment] 2019-04-16 16:50
More generally, it would be good to have variants build with and without mpi.

See https://conda.io/projects/conda-build/en/latest/resources/variants.html

**Comment by CyrilleBonamy** [comment] 2019-04-16 19:33
> More generally, it would be good to have variants build with and without mpi.
> 
> See https://conda.io/projects/conda-build/en/latest/resources/variants.html

Yes. Currently there are two variants: one with openmpi and another with mpich ... Each variant has been compiled for linux, and for macos.
Which variants do you want?

Concerning Windows, the problem is the support of dependencies (pythran...).

**Comment by paugier** [comment] 2019-04-18 07:58
In terms of MPI: openmpi, mpich and nompi. On Windows, only nompi.

For Windows, you are right that we first need to get a Pythran package for Windows. It should be doable since it works fine locally.

**Comment by ashwinvis** [comment] 2020-12-04 14:20
Now we have nompi build on Windows. We have disabled both Pythran and Cython extensions for the time being.

https://foss.heptapod.net/fluiddyn/fluidfft/-/issues/29

**Comment by ashwinvis** [comment] 2024-02-14 08:52
@paugier It seems to me now with 9f3a65e12d4b91491cc49f1b25296c1a425feb44 Windows no-MPI build has Pythran extensions also. Closing this and also the old attempt #5

**Closed as completed by ashwinvis** 2024-02-14 08:52 UTC
